volumes:
  postgres_data: {}
  postgres_data_backups: {}
  redis_data: {}
  node_modules: {}

services:
  backend:
    command: "python manage.py runserver_plus 0.0.0.0:8000"
    build:
      context: ../backend
      dockerfile: ../backend/docker/Dockerfile
    depends_on:
      - postgres
    volumes:
      - ../backend:/app
    environment:
      - DJANGO_FRONTEND_URL=http://localhost:3000
    env_file:
      - ./conf/${LOCAL_ENV:-default}
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ../frontend
      dockerfile: ./docker/Dockerfile
      target: development
    env_file:
      - ./conf/${LOCAL_ENV:-default}
    volumes:
      - node_modules:/app/node_modules
      - ../frontend:/app
    depends_on:
      - backend
    ports:
      - "3000:3000"

  postgres:
    image: postgres:${POSTGRES_VERSION:-16}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/backups
    env_file:
      - ./conf/${LOCAL_ENV:-default}
    ports:
      - "5432:5432"
